### ISSUE TITLE
[NFP 1.3.0] ModuleManager warning for NearFuturePropulsionWaterfallHallEffect

### ISSUE THREAD

**Issue by LouisB3** [post-kerbin-mining-corporation/NearFuturePropulsion#122]
From log:

`[WRN 11:48:25.023] more than one pass specifier detected, ignoring all but the first: NearFuturePropulsion/Patches/Waterfall/NearFuturePropulsionWaterfallHallEffect/@PART[ionArgon-0625]:NEEDS[Waterfall]:FOR[NearFuturePropulsion]:FOR[NearFuturePropulsion]`
...
`[WRN 11:48:42.072] 1 warning related to GameData/NearFuturePropulsion/Patches/Waterfall/NearFuturePropulsionWaterfallHallEffect.cfg`

**Comment by Bornholio** [comment]
confirm same error after updating this morning

**Comment by Bornholio** [comment]
NearFuturePropulsionWaterfallHallEffect.cfg line 1:
`@PART[ionArgon-0625]:NEEDS[Waterfall]:FOR[NearFuturePropulsion]:FOR[NearFuturePropulsion]`

**Comment by ChrisAdderley** [comment]
Was harmless, but also was fixed by above!
