### ISSUE TITLE
Broken waterfall configs on two hall effect thrusters and 2.5m MPDT

### ISSUE THREAD

**Issue by LeopardEnthusiast** [post-kerbin-mining-corporation/NearFuturePropulsion#129]
The following engines have broken waterfall configs, with no module shown in the waterfall editor:
* GW7201 'Gyro-2' Lensed Hall Thruster
* GW3 'Triplet' Nested-Channel Hall Thruster
* LF-9 'Colossus' Magnetoplasmadynamic Engine

**Comment by ChrisAdderley** [comment]
Sorted out in last release
