### ISSUE TITLE
Error during loading

### ISSUE THREAD

**Issue by Matthias32** [post-kerbin-mining-corporation/NearFuturePropulsion#136]
Hi,

I had an error while loading the game I'm not sure if it is related to this mod. I'm using the newest RP1 express install on KSP 1.12.3 together with this mod from ckan. 

1 error related to GameData/KerbalismConfig/Support/NearFuture.cfg
2 errors related to GameData/KerbalismConfig/Support/SXT.cfg

**Comment by ChrisAdderley** [comment]
Kerbalism issue or RP1 issue -> RP1 or Kerbalism repos
